---
title: "static_model"
author: "Mateus Aguilar"
date: "`r format(Sys.Date(), '%d-%m-%Y')`"
output: html_document
---
```{r}
#library(brms)
unloadNamespace("FootStats")
```

```{r}
# Categorização de variáveis
df_test$Y <- factor(df_test$resultado, 
                     levels = c(0, 1, 2), 
                     labels = c("L", "D", "W"))
df_train$Y <- factor(df_train$resultado, 
                     levels = c(0, 1, 2), 
                     labels = c("L", "D", "W"))
```


```{r Modelo logal, include=FALSE}
log <- brm(Y ~  (0 + atk | team_name) + (0 + def | opponent) + home:team_name, 
                data = df_train, 
                family = categorical(link = 'logit', 
                                     refcat = 'L'))
summary(log)
a = ranef(log)
```

```{r Fatores}
# atk_W = data.frame(atk_W = a$team_name[, 'Estimate', 'muW_atk'], team_name = row.names(a$team_name[, ,  'muW_atk']))
# atk_D = data.frame(atk_D = a$team_name[, 'Estimate', 'muD_atk'], team_name = row.names(a$team_name[, ,  'muD_atk']))
# def_W = data.frame(def_W = a$opponent[, 'Estimate', 'muW_def'], opponent = row.names(a$opponent[, , 'muW_def']))
# def_D = data.frame(def_D = a$opponent[, 'Estimate', 'muD_def'], opponent = row.names(a$opponent[, , 'muD_def']))
# home_W = data.frame(home_W = a$team_name[, 'Estimate', 'muW_home'], team_name = row.names(a$team_name[, ,  'muW_home']))
# home_D = data.frame(home_D = a$team_name[, 'Estimate', 'muD_home'], team_name = row.names(a$team_name[, ,  'muD_home']))
```

```{r}
c = coef(log)

table <- df_train %>% 
  select(gf, ga, round, venue, team_name, opponent) %>% 
  #bind_cols(vars2) %>% 
  bind_cols(predict(log)) #%>% 
  # merge(atk_W, by = 'team_name') %>% 
  # merge(atk_D, by = 'team_name') %>% 
  # merge(def_W, by = 'opponent') %>%
  # merge(def_D, by = 'opponent') %>%
  # merge(home_W, by = 'team_name') %>% 
  # merge(home_D, by = 'team_name')

#View(table)
```

```{r}
df_train <- df_train %>% 
  select(gf, ga, round, venue, team_name, opponent, home, atk, def, resultado, Y)

df_train <- df_train %>% 
           merge(
             table %>% select(team_name, opponent, round, 
                              `P(Y = L)`,`P(Y = D)`,`P(Y = W)`), 
             by = c('round', 'team_name', 'opponent')
             )

df_train2 <- df_train %>% subset(venue == 'Home')
```

```{r}
df_test <- df_test %>% 
  select(gf, ga, round, venue, team_name, opponent, home, atk, def, resultado, Y)

df_test <- df_test %>%
            bind_cols(
            predict(log, df_test, type = "probs") %>%
            as.data.frame() %>%
            setNames(c("P_LOSS", "P_DRAW", "P_WIN"))
            )

df_test2 <- df_test %>% subset(venue == 'Home')
```

```{r Matriz de confusão e Acurácia}
# Define o label previsto como aquele com maior probabilidade
prob = table(df_train2$Y)/length(df_train2$Y) 
df_train2$P_LOSS_adj = df_train2$`P(Y = L)` / prob[1]
df_train2$P_DRAW_adj = df_train2$`P(Y = D)` / prob[2]
df_train2$P_WIN_adj = df_train2$`P(Y = W)` / prob[3]

df_train2 <- df_train2 %>%
    mutate(
    y_hat = case_when(
      P_LOSS_adj >= P_DRAW_adj & P_LOSS_adj >= P_WIN_adj ~ "L",
      P_DRAW_adj  >= P_LOSS_adj & P_DRAW_adj  >= P_WIN_adj ~ "D",
      P_WIN_adj >= P_LOSS_adj & P_WIN_adj >= P_DRAW_adj  ~ "W"
    )
  )

# Matriz de Confusão
conf_matrix <- table(Real = factor(df_train2$Y, levels = c("L", "D", "W")),
                     Predito = factor(df_train2$y_hat, levels = c("L", "D", "W")))

print(conf_matrix)

# Acurácia
acc <- sum(diag(conf_matrix)) / sum(conf_matrix)
print(paste("Acurácia geral:", round(acc, 4)))

```

```{r Matriz de confusão e Acurácia}
# Define o label previsto como aquele com maior probabilidade
df_test2 <- df_test2 %>%
  mutate(
    P_LOSS_adj = P_LOSS / p[1],
    P_DRAW_adj = P_DRAW / p[2],
    P_WIN_adj = P_WIN / p[3],
    y_hat = case_when(
      P_LOSS_adj >= P_DRAW_adj & P_LOSS_adj >= P_WIN_adj ~ "L",
      P_DRAW_adj  >= P_LOSS_adj & P_DRAW_adj  >= P_WIN_adj ~ "D",
      P_WIN_adj >= P_LOSS_adj & P_WIN_adj >= P_DRAW_adj  ~ "W"
    )
  )

# Matriz de Confusão
conf_matrix <- table(Real = factor(df_test2$Y, levels = c("L", "D", "W")),
                     Predito = factor(df_test2$y_hat, levels = c("L", "D", "W")))

print(conf_matrix)

# Acurácia
acc <- sum(diag(conf_matrix)) / sum(conf_matrix)
print(paste("Acurácia geral:", round(acc, 4)))

```
