---
title: "static_model"
author: "Mateus Aguilar"
date: "`r format(Sys.Date(), '%d-%m-%Y')`"
output: html_document
---
```{r}
#rm(list=ls())
library("mixcat")
```

```{r}
df_train$Y <- factor(df_train$resultado, levels = c(0, 1, 2), labels = c("L", "D", "W"))
```


```{r Modelo multal, include=FALSE}
attach(df_train)

# Y
# team_name

mult <- npmlt(Y ~ 1,
              formula.npo = ~ -1 + (0 + atk + home| team_name) + (0 + def | opponent),
              k = 1)
summary(mult)
a = ranef(mult)

detach(df_train)
```

```{r Fatores}
atk = data.frame(atk = a$cond$team_name$atk, team_name = row.names(a$cond$team_name))
def = data.frame(a$cond$opponent, opponent = row.names(a$cond$opponent))
home = data.frame(home = a$cond$team_name$home, team_name = row.names(a$cond$team_name))
```

```{r}
c = coef(mult)
#d = c$cond$team_name[1, c("(Intercept)", "home")]
#d = c$cond$team_name[1, c("(Intercept)")]
vars <- data.frame(model.matrix(mult)) 
#vars2 <- data.frame('Intercept' = vars[,1] * d[1,1], 'home' =  vars[,2] * d[1,2])
#vars2 <- data.frame('Intercept' = vars[,1] * d[1])

table <- df_train %>% 
  select(gf, ga, round, venue, team_name, opponent) %>% 
  #bind_cols(vars2) %>% 
  bind_cols(data.frame(Predito = predict(mult))) %>% 
  merge(atk, by = 'team_name') %>% 
  merge(def, by = 'opponent') %>% 
  merge(home, by = 'team_name')

#View(table)
```

```{r}
df_test <- df_test %>% 
  select(gf, ga, round, venue, team_name, opponent, home, atk, def, resultado)

# Previsões para resultados (pi_hat)
df_test$pi_hat <- predict(mult, df_test, type = "response")

df_test2 <- df_test %>% subset(venue == 'Home')

df_test2$Y <- ifelse(df_test2$resultado == 0, 0, 1)
```

```{r}
G = 100
grid <- (1:G)/G  # função 


M <- matrix(NA, nrow = NROW(df_test2), ncol = G)

for(j in 1:G){
  M[, j] = ifelse(df_test2$pi_hat >= grid[j], 1, 0)
}

M2 <- matrix(NA, nrow = G, ncol = 4)

for(i in 1:G){
  M2[i, 1] = mean((M[, i] == 1) & (df_test2$Y == 1))    # sensibilidade
  M2[i, 2] = mean((M[, i] == 0) & (df_test2$Y == 0))    # especificidade
  M2[i, 3] = mean(M[, i] == df_test2$Y)                 # acurácia
}
# M2[, 4] = M2[, 1] + M2[, 2] - 1                         # Indice de Youden
M2[, 4] = (M2[, 1] + M2[, 2])/2                         # acurácia balanceada

# M2

# classificador
K <- max(which(M2[, 4] == max(M2[, 4])))
#df_test2$y_hat = M[, min(which(M2[, 4] == max(M2[, 4])))]
df_test2$y_hat = M[, max(which(M2[, 4] == max(M2[, 4])))]
```


```{r Matriz de confusão e Acurácia}
# Classificando vitória (2), empate (1) ou derrota (0)
# Fatores de corte
#df_test2$gd_hat <- df_test2$gf_hat - df_test2$ga_hat
#t1 = 0.07
#t2 = 0.50

#df_test2$pred_result <- factor(ifelse(df_test2$gd_hat > t2, 2,
#                                      ifelse(df_test2$gd_hat < t1, 0, 1)))

# Matriz de Confusão
conf_matrix <- table(Predito = df_test2$y_hat, Real = df_test2$Y)
print(conf_matrix)

# Acurácia geral
print(paste("Acuracia: ", M2[K, 3]))
print(paste("Sensibilidade: ", M2[K, 1]))
print(paste("Especificidade: ", M2[K, 2]))
print(paste("Acuracia balanceada: ", M2[K, 4]))
```
