```{r}
#rm(list=ls())

#library(tidyverse)
library(rstan)
#library(bayesplot)
unloadNamespace("FootStats")

options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE) 
```


```{r}
unique_teams <- unique(c(df_train$team_name, df_train$opponent))

df_train <- df_train %>% 
            mutate(
              team_name_index = match(team_name, unique_teams),
              opponent_index = match(opponent, unique_teams)
            )
df_test<- df_test %>% 
            mutate(
              team_name_index_new = match(team_name, unique_teams),
              opponent_index_new = match(opponent, unique_teams)
            )
```


# Fit

```{r}
data = list(
  nteams = length(unique(df_train$team_name_index)),
  ngames = nrow(df_train),
  nrounds = max(c(df_train$round, df_test$round)),
  i_round = df_train$round,
  gf = df_train$gf,
  ga = df_train$ga,
  team_name_index = df_train$team_name_index,
  opponent_index = df_train$opponent_index,
  
  # test
  ngames_new = nrow(df_test),
  i_round_new = df_test$round,
  team_name_index_new = df_test$team_name_index_new,
  opponent_index_new = df_test$opponent_index_new
)
```


```{r}
model_norm = stan_model("../models/dynamic_normal.stan", model_name = "dynamic_normal")

iter = 100 # rodar com 10000 para conferir [!]
chains = 4
cores = 4
control = list(max_treedepth = 15)

fit_norm = sampling(model_norm,
              data = data,
              iter = iter,
              chains = chains,
              cores = cores,
              control = control,
              refresh = 100
              )
saveRDS(fit_norm, "../results/dynamic_normal.rds")
fit_norm = readRDS("../results/dynamic_normal.rds")
```

```{r}
print(fit_norm)
```


# Analysis

```{r}
traceplot(fit_norm, inc_warmup = TRUE, pars = c("att[1,2]"))
```


# Simulations

```{r}
# ----------------------------
# Função para encontrar os limiares ótimos no treino
# ----------------------------
find_thresholds <- function(df_train2) {
  G <- 100
  grid <- seq(min(df_train2$gd_hat), max(df_train2$gd_hat), length.out = G)
  
  M <- matrix(0, nrow = G, ncol = G)
  
  for(i in 1:G){
    for(j in i:G){
      M[i, j] <-
        ( sum((df_train2$gd_hat <= grid[i]) & (df_train2$Y == 'L')) / sum(df_train2$Y == 'L') +
          sum((df_train2$gd_hat > grid[i] & df_train2$gd_hat < grid[j]) & (df_train2$Y == 'D')) / sum(df_train2$Y == 'D') +
          sum((df_train2$gd_hat >= grid[j]) & (df_train2$Y == 'W')) / sum(df_train2$Y == 'W')
        ) / 3
    }
  }
  
  indices_max <- which(M == max(M, na.rm = TRUE), arr.ind = TRUE)
  
  taus <- matrix(NA, nrow = NROW(indices_max), ncol = 2)
  for(k in 1:NROW(indices_max)){
    taus[k, ] <- c(grid[indices_max[k, 1]], grid[indices_max[k, 2]])
  }
  
  taus_diff <- taus[, 2] - taus[, 1]
  tau_max_diff <- which(taus_diff == max(taus_diff))
  
  t1 <- taus[tau_max_diff, 1]
  t2 <- taus[tau_max_diff, 2]
  
  return(c(t1 = t1, t2 = t2))
}

# ----------------------------
# Função para classificar com base nos limiares
# ----------------------------
classify_results <- function(df, t1, t2) {
  df <- df %>%
    mutate(y_hat = factor(
      ifelse(gd_hat <= t1, 'L',
             ifelse(gd_hat >= t2, 'W', 'D')),
      levels = c("L", "D", "W")
    ))
  return(df)
}

# ----------------------------
# Função para calcular matriz de confusão e acurácia
# ----------------------------
evaluate_accuracy <- function(df) {
  conf_matrix <- table(Real = df$Y, Predito = df$y_hat)
  print(conf_matrix)
  
  acc_total <- sum(diag(conf_matrix)) / sum(conf_matrix)
  cat("Acurácia geral:", round(acc_total, 4), "\n")
  
  classes <- c("W", "D", "L")
  acc_per_class <- sapply(classes, function(classe) {
    idx <- which(df$Y == classe)
    mean(df$y_hat[idx] == df$Y[idx])
  })
  acc_df <- data.frame(Classe = classes, Acuracia = round(acc_per_class, 4))
  print(acc_df)
  
  return(list(conf_matrix = conf_matrix, acc_total = acc_total, acc_per_class = acc_df))
}

```


```{r}
# ----------------------------
# 1. Extrair médias preditas do modelo Stan
# ----------------------------
samples <- rstan::extract(fit_norm)

gf_hat_train <- colMeans(samples$theta1)
ga_hat_train <- colMeans(samples$theta2)
gf_hat_test  <- colMeans(samples$theta1_new)
ga_hat_test  <- colMeans(samples$theta2_new)

# ----------------------------
# 2. Criar dataframes com variáveis preditas
# ----------------------------
df_train2 <- df_train %>%
  mutate(
    gf_hat = gf_hat_train,
    ga_hat = ga_hat_train,
    gd_hat = gf_hat - ga_hat,
    Y = factor(resultado, levels = c(0, 1, 2), labels = c("L", "D", "W"))
  ) %>%
  filter(venue == "Home")

df_test2 <- df_test %>%
  mutate(
    gf_hat = gf_hat_test,
    ga_hat = ga_hat_test,
    gd_hat = gf_hat - ga_hat,
    Y = factor(resultado, levels = c(0, 1, 2), labels = c("L", "D", "W"))
  ) %>%
  filter(venue == "Home")

# ----------------------------
# 3. Encontrar os limiares ótimos no treino
# ----------------------------
thresholds <- find_thresholds(df_train2)
t1 <- thresholds["t1"]
t2 <- thresholds["t2"]
cat("Limiar t1:", t1, "\n")
cat("Limiar t2:", t2, "\n")

# ----------------------------
# 4. Classificar com base nos limiares
# ----------------------------
df_train2 <- classify_results(df_train2, t1, t2)
df_test2  <- classify_results(df_test2, t1, t2)

# ----------------------------
# 5. Avaliar desempenho no treino e teste
# ----------------------------
cat("\nAvaliação no treino:\n")
train_results <- evaluate_accuracy(df_train2)

cat("\nAvaliação no teste:\n")
test_results <- evaluate_accuracy(df_test2)
```

